# Generated by Django 5.2.4 on 2025-10-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, help_text='Optional full name used for display purposes.', max_length=150, null=True),
        ),
    ]
